// User
export const USER_ROOT_TOPIC = "USER";
export const USER_PROFILE_GET_TOPIC = "USER.GET_PROFILE";
export const  USER_PROFILE_UPDATE_TOPIC = "USER.PROFILE_UPDATE";

// Auth
export const AUTH_ROOT_TOPIC = "AUTH";
export const AUTH_LOGIN_TOPIC = "AUTH.LOGIN";
export const AUTH_LOGOUT_TOPIC = "AUTH.LOGOUT";
export const AUTH_REGISTER_TOPIC = "AUTH.REGISTER";

// Task
export const TASK_ROOT_TOPIC = "TASK";
export const TASK_ADD_TOPIC = "TASK.ADD";
export const TASK_DELETE_TOPIC = "TASK.DELETE";
export const TASK_UPDATE_TOPIC = "TASK.UPDATE";

// Project
export const PROJECT_ROOT_TOPIC = "PROJECT";
export const PROJECT_ADD_TOPIC = "PROJECT.ADD";
export const PROJECT_DELETE_TOPIC = "PROJECT.DELETE";
export const PROJECT_UPDATE_TOPIC = "PROJECT.UPDATE";

// Error
export const ERROR_ROOT_TOPIC = "ERROR";
export const ERROR_MSG_INFO_TOPIC = "ERROR.MSG_INFO";
export const ERROR_MSG_WARN_TOPIC = "ERROR.MSG_WARN";
export const ERROR_MSG_ERROR_TOPIC = "ERROR.MSG_ERROR";

// Notification
export const NOTIFICATION_ROOT_TOPIC = "NOTIFICATION";
export const NOTIFICATION_MSG_INFO_TOPIC = "NOTIFICATION.MSG_INFO";
export const NOTIFICATION_MSG_WARN_TOPIC = "NOTIFICATION.MSG_WARN";
export const NOTIFICATION_MSG_ERROR_TOPIC = "NOTIFICATION.MSG_ERROR";
