export const topics = {
  // User
  USER_ROOT: "USER",
  USER_PROFILE_GET: "USER.GET_PROFILE",
  USER_PROFILE_UPDATE: "USER.PROFILE_UPDATE",

  // Auth
  AUTH_ROOT: "AUTH",
  AUTH_LOGIN: "AUTH.LOGIN",
  AUTH_LOGOUT: "AUTH.LOGOUT",

  // Tasks
  TASK_ROOT: "TASK",
  TASK_ADD: "TASK.ADD",
  TASK_DELETE: "TASK.DELETE",
  TASK_UPDATE: "TASK.UPDATE",

  // Projects
  PROJECT_ROOT: "PROJECT",
  PROJECT_ADD: "PROJECT.ADD",
  PROJECT_DELETE: "PROJECT.DELETE",
  PROJECT_UPDATE: "PROJECT.UPDATE",

  // Errors
  ERROR_ROOT: "ERROR",
  ERROR_MSG_INFO: "ERROR.MSG_INFO",
  ERROR_MSG_WARN: "ERROR.MSG_WARN",
  ERROR_MSG_ERROR: "ERROR.MSG_ERROR",

  // Notifications
  NOTIFICATION_ROOT: "NOTIFICATION",
  NOTIFICATION_MSG_INFO: "NOTIFICATION.MSG_INFO",
  NOTIFICATION_MSG_WARN: "NOTIFICATION.MSG_WARN",
  NOTIFICATION_MSG_ERROR: "NOTIFICATION.MSG_ERROR",
}

export const api = {
  API_BASE_URL: "/api",

  // Tasks
  API_TASKS_URL: "/tasks",

  // Projects
  API_PROJECTS_URL: "/projects",

  // Companies
  API_COMPANIES_URL: "/companies",

  // AUTH
  API_AUTH_LOGIN_URL: "/auth/login",
  API_AUTH_LOGOUT_URL: "/auth/logout",
  API_AUTH_REGISTER_URL: "/auth/register",
}
